### ISSUE TITLE
GDPR ability to pull non personalised ad where cookie permission denied

### ISSUE THREAD

**Issue by jamiecarter7** [mazipan/vue-google-adsense#10]
It looks like there is a data tag that allows a non- personalised ad to be pulled from google in the event a person denies the allowing of cookies. 

Is this possible with vga plugin?

**Comment by mazipan** [comment]
Can you give me sample or link @jamiecarter7 ?

**Comment by jamiecarter7** [comment]
Ok, so I did some digging.

This seems to be a good area to look.

https://support.google.com/adsense/answer/9042142?hl=en&ref_topic=7670012

**Comment by mazipan** [comment]
Adding new props `is-non-personalized-ads` in v1.4.0
