### ISSUE TITLE
data-ad-format option

### ISSUE THREAD

**Issue by airnichols13** [mazipan/vue-google-adsense#14]
Hi again,

I noticed one more thing that may be useful to add (if I think what is happening is actually happening):

The responsive CSS I'm putting on the classes that go on the `<ins>` element are getting overridden, I believe by the presence of `data-ad-format="auto"`. Looking at the adsense code I'm using on my current site vs the code your package creates, that seems to be the most meaningful difference.

Do you think that could be what's overriding my styles? If so, could `data-ad-format` become an option like the other `data-ad-xxx` options (with the option to turn it off with `null`)?

Thanks again for all your help!

**Comment by mazipan** [comment]
Sure, but now is holiday in Jakarta.
So maybe tommorow I will work on this

**Comment by airnichols13** [comment]
Hi - any luck with this?

**Comment by mazipan** [comment]
Sorry, I have sick from Saturday (Jakarta Time).
Today I hope I can work for this feature.
Will update in this issue if any progress.

**Comment by mazipan** [comment]
Released on v1.5.0 ya @airnichols13

**Comment by airnichols13** [comment]
Look like what you did is working, but IE11 is broken again:

`Object doesn't support property or method 'assign'`

I'm guessing it's a transpiling thing again?

**Comment by mazipan** [comment]
Fix in https://github.com/mazipan/vue-google-adsense/commit/7bdf5032c5dd71e5baaa506f17c373077f8ab545

**Comment by airnichols13** [comment]
That worked - thanks again!
