### ISSUE TITLE
Ad revenue 20% of what it was before vue-googgle-adsense

### ISSUE THREAD

**Issue by airnichols13** [mazipan/vue-google-adsense#141]
Hello,

I started using vue-google-adsense about a year ago and ever since then, my ad revenue has gone down every month, and now is about 20% of what it used to be.

Am I doing something wrong?

My website is [whichcarisrightforme.com](http://www.whichcarisrightforme.com/).

Thanks,
Chris

**Comment by mazipan** [comment]
I don't know about the revenue stats things.
I just make sure the ads is show up.

**Comment by airnichols13** [comment]
Well, I have noticed the ads don't show sometimes, although I'm not sure why. Maybe that is contributing to the decrease.

Also, is there a way to reinitialize the ads of a component? I don't see that in the documentation.

**Comment by mazipan** [comment]
Yes, we can not refresh the ads.
One of the way is using hard refresh.

**Comment by mazipan** [comment]
Closed this since I didn't have idea about this.
