### ISSUE TITLE
Error with multiple "adsbygoogle" definition

### ISSUE THREAD

**Issue by kernel-picnic** [mazipan/vue-google-adsense#143]
Hello. I got an error on my website:
```
adsbygoogle.push() error: All ins elements in the DOM with class=adsbygoogle already have ads in them.
```

As mentioned in this issue https://github.com/mazipan/vue-google-adsense/issues/73#issuecomment-546686432, I found that here probably need to add `v-else`: [link](https://github.com/mazipan/vue-google-adsense/blob/b8ec3e6fa232dd2dba89de22e4fb01e10d0adc38/src/ads/AdsenseComponent.vue#L21). What do you think?

**Comment by dmyers** [comment]
Also experiencing this.

**Comment by NRiebesel** [comment]
Same here. Any updates on this? Thanks!

**Comment by pradyotghosh** [comment]
+1

**Comment by mazipan** [comment]
Should be fix using the latest version
