### ISSUE TITLE
runtime-only build of Vue

### ISSUE THREAD

**Issue by binaamir** [mazipan/vue-google-adsense#2]
Hi I am trying to use this plugin when I place the component in my code i got the following warning in console and my ads are not displaying: 

[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build. 
found in 
---> <Script2> 
           <Adsense> 
              <BusinessesList> at src\components\Businesses\BusinessesList.vue 
                 <Business> at src\components\Businesses\Business.vue 
                   <QLayout> 
                       <Main> at src\components\Main.vue 
                         <App> at src\App.vue 
                           <Root>

I am building PWA. Please help me how to fix this issue.

**Comment by mazipan** [comment]
Can you show me how you using this code @binaamir ? because I already use this Plugin in several projects and work well.

**Comment by lucassbgomes** [comment]
I had the same problem, after much reading, testicles, I managed to solve. In my case, I was using quasar + pwa + vue-google-adsense. For some reason, in webpack quasar (./config/index.js) does not have the alias that vue models have:

> 'vue $': 'vue / dist / vue.esm.js'

After inserting this line in webapck.base.conf.js, it worked 100%. I hope this helps.
