### ISSUE TITLE
Nuxt.js Integration

### ISSUE THREAD

**Issue by dse102** [mazipan/vue-google-adsense#29]
I've followed the nuxt.js install steps but when adsense scans my site it gets returns this message.

> We couldn’t find the code on your site. This is because the code is either missing or incomplete, or because the URL of your site is incorrect. Learn more.
> 
> Copy and paste this code in the HTML of your site, between the <head> and </head> tags.

I may be confused around the update nuxt.config.js directions.  I've added line line of code liek below
```
plugins: [
    { src:'~/plugins/vue-material'   },
    { src:'~/plugins/axios'},
    {src:'~plugins/firestore'},
    { src: '~/plugins/vue-google-adsense', ssr: false }
   
  ],
```
because I didn't have a module.exports section.  Am I missing something?  Thanks

**Comment by GuoGuang0536** [comment]
I ran into the same problem, I think it must be placed between the <HEAD> and </HEAD> tags.

**Comment by rlam3** [comment]
@GuoGuang0536 Did you find a workaround? I'm still having the same problem ....

**Comment by mazipan** [comment]
First, make sure you install the latest version.
Second, you can follow the instructions in readme or looking to my project https://github.com/mazipan/blog-2.0 that using Nuxt.js and already implementing Google AdSense with this library.
