### ISSUE TITLE
[1.6.1]enable_page_level_ads' allowed per page

### ISSUE THREAD

**Issue by 158008001** [mazipan/vue-google-adsense#43]
Vue relies on the updated version to 1.6.1。
At present, all the ads cannot be displayed, and the console reports an error:
vue-google-adsense adsbygoogle.push() error: Only one 'enable_page_level_ads' allowed per page.

**Comment by mazipan** [comment]
Got it.

**Comment by mazipan** [comment]
Try to updating the last version
