### ISSUE TITLE
[feature request] Google Adsense Integration for VuePress...

### ISSUE THREAD

**Issue by m3andros** [mazipan/vue-google-adsense#7]
Is there a way to implement Adsense for VuePress, please?

**Comment by mazipan** [comment]
From this link https://vuepress.vuejs.org/guide/basic-config.html#app-level-enhancements
You can create file `.vuepress/enhanceApp.js` with code like this:

```js
export default ({
  Vue, // the version of Vue being used in the VuePress app
  options, // the options for the root Vue instance
  router, // the router instance for the app
  siteData // site metadata
}) => {
  // ...apply enhancements to the app
  // ...install additional plugin here
}
```

**Comment by m3andros** [comment]
Thanks for the assistance @mazipan. I've gotten it to work, except I am now getting this error:
```Failed to load resource: the server responded with a status of 400 ()```

Not sure what the error means, since the Adsense ad isn't loading. Only a hollow white space is displaying. I've added the following to "test" the ad: `data-adtest="on"`

Any help you can provide would be most helpful!

Thank you.

**Comment by mazipan** [comment]
Hmmm, white space is not always because this plugin not working.
Sometimes it because your Adsense not work properly.

Just inspect element and make sure you can found this kind of element:

```html
<ins data-ad-client="ca-pub-XXXXXXX" data-ad-slot="XXXXXX" data-ad-test="" data-ad-format="auto" class="adsbygoogle" data-adsbygoogle-status="done" style="display: block; height: 90px;">
....any child here
</ins>
```

<img width="750" alt="screen shot 2018-09-05 at 14 39 18" src="https://user-images.githubusercontent.com/7221389/45078321-ef300300-b119-11e8-9c68-a899ecdbe135.png">

**Comment by marslord** [comment]
I got nothing wrong, only render  `<Adsense data-ad-client="ca-pub-xxx" data-ad-slot="xxx123"></Adsense>` in the page. My enhanceApp.js below: 

```
export default ({
    Vue, // the version of Vue being used in the VuePress app
    options, // the options for the root Vue instance
    router, // the router instance for the app
    siteData // site metadata
}) => {
    // ...apply enhancements to the app
    Vue.use(require('vue-script2'))

    Vue.use(require('vue-google-adsense/dist/Adsense.min.js'))

    // Vue.use(require('vue-google-adsense/dist/InArticleAdsense.min.js'))

    // Vue.use(require('vue-google-adsense/dist/InFeedAdsense.min.js'))
}
```
@m3andros  Hi man. Could you share a demo code for showing how it works? 
Thank you in advance!
