### ISSUE TITLE
Vuejs Issue. Nothing shows

### ISSUE THREAD

**Issue by lipecss** [mazipan/vue-google-adsense#82]
I performed all the installation procedures, created the ad on the platform, added the component, but nothing appears. I'm testing locally, so it doesn't work?

**Comment by mazipan** [comment]
Of course, Adsense can only show on the website url that already validated.
Will not work on the local.

**Comment by lipecss** [comment]
How do i Know that IS working??

**Comment by mazipan** [comment]
Just deploy it.
Or you can edit your etc host file to directing to your local
